# This is the list of books for my libary project 3
# ""=>"",
book = {"Artemis Fowl"=>"Eoin Colfer",
"Chimera"=>"John Barth",
"Cats have no lord"=>"Will Shetterly",
"Aegypt"=>"John Crowley",
"Akata Witch"=>"Nnedi Okorafor","Akata Warrior"=>"Nnedi Okorafor",
"Aladore"=>"Henry Newbolt",
"Alice in Wonderland"=>"Lewis Carroll",
"The tales of alvin maker"=>"Orson Scott Card","Harts Hope"=>"Orson Scott Card",
"American gods"=>"Neil Gaiman","Coraline"=>"Neil Gaiman",
"Beauty"=>"Robin McKinley",
"The Lion, The witch, and the wardrobe"=>"C.S. Lewis","Prince Caspian: The Return to Narnia"=>"C.S. Lewis",
"The Voyage of the Dawn Treader"=>"C.S. Lewis","The Silver Chair"=>"C.S. Lewis","The Horse and his Boy"=>"C.S. Lewis",
"The Magicians Nephew"=>"C.S. Lewis","The Last battle"=>"C.S. Lewis",
"City of Bones"=>"Martha Wells","The Death of the Necromancer"=>"Martha Wells",
"The Fall of Iie-Rien"=>"Martha Wells","The Element of fire"=>"Martha Wells",
"The Dark Tower:The gunsligner"=>"Stephen King","The Little Sisters of Eluria"=>"Stephen King",
"The Dark Tower II: The Drawing of the Three"=>"Stephen King","The Dark Tower III: The Waste Lands"=>"Stephen King",
"The Dark Tower IV: Wizard and Glass"=>"Stephen King","The Dark Tower: The Wind through the Keyhole"=>"Stephen King",
"The Dark Tower V: Wolves of the Dalla"=>"Stephen King","The Dark Tower VI: Song of Susannah"=>"Stephen King",
"The Dark Tower VI: The Dark Tower"=>"Stephen King","The Eyes of the Dragon"=>"Stephen King",
"Discworld"=>"Terry Pratchett",
"Word & Void"=>"Terry Brooks","The Genesis of Shannara"=>"Terry Brooks",
"First King of Shannara"=>"Terry Brooks","The Sword of Shannara"=>"Terry Brooks",
"The Heritage of Shannara"=>"Terry Brooks","The Voyage of the Jerle Shannara"=>"Terry Brooks",
"High Druid of Shannara"=>"Terry Brooks","The Dark Legacy of Shannara"=>"Terry Brooks",
"The Defenders of Shannara"=>"Terry Brooks","The Fall of Shannara"=>"Terry Brooks",
"Wizard for Hire"=>"Jim Butcher","Wizard by trade"=>"Jim Butcher","Wizard at Large"=>"Jim Butcher",
"Wizard under Fire"=>"Jim Butcher","Small Favor"=>"Jim Butcher","Turn Coat"=>"Jim Butcher",
"Changes"=>"Jim Butcher","Ghost Story"=>"Jim Butcher","Cold days"=>"Jim Butcher",
"Skin Game"=>"Jim Butcher","Peace Talks"=>"Jim Butcher","Battle Grounds"=>"Jim Butcher",
"Elantris"=>"Brandon Sanderson",
"The Fool on the hill"=>"Matt Ruff",
"Eragon"=>"Christopher Paolini","Eldest"=>"Christopher Paolini","Brisingr"=>"Christopher Paolini",
"Inheritance"=>"Christopher Paolini",
"Excalibur"=>"Sanders Anne Laubenthal",
"The Last Hero"=>"Rick Riordan","The Son of Neptune"=>"Rick Riordan","The House of Hades"=>"Rick Riordan",
"The Blood of Olympus"=>"Rick Riordan","The Red Pyramid"=>"Rick Riordan","The Throne of Fire"=>"Rick Riordan",
"The Serpent's Shadow"=>"Rick Riordan","The Lighting Theif"=>"Rick Riordan",
"The Sea of Monsters"=>"Rick Riordan","The Titan's curse"=>"Rick Riordan",
"The Battle of the Labyrinth"=>"Rick Riordan","The Last Olympian"=>"Rick Riordan",
"The Hobbit"=>"J.R.R. Tolkien","The Fellowship of the Ring"=>"J.R.R. Tolkien",
"The Two Towers"=>"J.R.R. Tolkien","The Return of the King"=>"J.R.R. Tolkien",
"The Lost tales"=>"J.R.R. Tolkien",
"Howl's Moving Castle"=>"Diana Wynn Jones",
"The Name of the Wind"=>"Patrick Rothfuss","The Wise Man's Fear"=>"Patrick Rothfuss",
"The Doors of Stone"=>"Patrick Rothfuss",
"Legends & Lattes"=>"Travis Baldree",
"The Poppy War"=>"R.F. Kuang"}

author = {"Eoin Colfer"=>"01","John Barth"=>"02",""=>"03","John Crowley"=>"04",
"Nnedi Okorafor"=>"05","Henry Newbolt"=>"06","Lewis Carroll"=>"07","Orson Scott Card"=>"08",
"Neil Gaiman"=>"09","Robin McKinley"=>"10","C.S. Lewis"=>"11", "Martha Wells"=>"12","Stephen King"=>"13",
"Terry Pratchett"=>"14","Jim Butcher"=>"15","Brandon Sanderson"=>"16","Christopher Paolini"=>"17",
"Sanders Anne Laubenthal"=>"18","Matt Ruff"=>"19","Rick Riordan"=>"20","J.R.R. Tolkien"=>"21",
"Diana Wynn Jones"=>"22","Patrick Rothfuss"=>"23","Terry Brooks"=>"24","R.F. Kuang"=>"25",
"Travis Baldree"=>"26"}